version: '3'

services:
  chrome:
    image: selenium/standalone-chrome
    platform: linux/x86_64
    networks:
      - my_network

  bot:
    image: r-kawano/rainbow-bot
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - chrome
    volumes:
      - ../src:/app/src
      - ../.env:/app/.env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge